name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tarpaulin:
    runs-on: ubuntu-latest
    env:
      PKCS11_SOFTHSM2_MODULE: /usr/lib/softhsm/libsofthsm2.so
    steps:
    - uses: actions/checkout@v2
    - name: SoftHSM installation
      run: |
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ focal universe"
        sudo apt-get install -f libsofthsm2
        sudo usermod -a -G softhsm $USER
    - name: tarpaulin installation
      run: |
        sudo apt-get install -f libssl-dev
        cargo install cargo-tarpaulin
    - name: coverage
      run: |
        sg softhsm -c \
          'cargo tarpaulin --verbose --out Xml'
    - name: codecov
      run: bash <(curl -s https://codecov.io/bash)
